<table>
	<tr>
		<td align='right'><?php echo $this->t_tariffname ?> :</td>
		<td><b><?php echo $this->tariffname ?></b></td>
	</tr>
	<tr>
		<td align='right'><?php echo $this->t_deposit ?> :</td>
		<td><b><?php echo $this->deposit ?></b></td>
	</tr>
	<tr>
		<td align='right'><?php echo $this->t_freebyte ?> :</td>
		<td><b><?php echo $this->freebyte ?></b></td>
	</tr>
	<tr>
		<td align='right'><?php echo $this->t_bonus ?> :</td>
		<td><b><?php echo $this->bonus ?></b></td>
	</tr>
	<tr>
		<td align='right'><?php echo $this->t_freemblimit ?> :</td>
		<td><b><?php echo $this->freemblimit ?></b></td>
	</tr>
	<tr>
		<td align='right'><?php echo $this->t_dateofcheck ?> :</td>
		<td><b><?php echo $this->dateofcheck ?></b></td>
	</tr>
</table>
