<div id="report">
    <div class="col-last">
        <div class="res-block">
            <div class="res-block-inner">
                <h3><?php echo $this->report ?></h3><br>
                <ul>
                    <li><a href="javascript:;" onclick="Reports.showStat()"><?php echo $this->connect ?></a></li>
                    <li><a href="javascript:;" onclick="Reports.showPayments()"><?php echo $this->payment ?></a></li>
                    <li><a href="javascript:;" onclick="Reports.showTariffs()"><?php echo $this->tariffs ?></a></li>
				</ul>
            </div>
        </div>
        <div class="res-block">
            <div class="res-block-inner">
                <h3><?php echo $this->site ?></h3><br>
                <ul>
					<li><a href="http://svs-tv.lan" target="blank"><?php echo $this->home ?></a></li>
					<li><a href="http://svs-tv.lan/forum" target="blank"><?php echo $this->forum ?></a></li>
                    <li><a href="http://stream.svs-tv.lan" target="blank"><?php echo $this->stream ?></a></li>
                    <li><a href="http://svs-tv.lan/foto" target="blank"><?php echo $this->foto ?></a></li>
	 	            <li><a href="http://games.svs-tv.lan/cs16" target="blank"><?php echo $this->cs16 ?></a></li>
				</ul>
				
            </div>
        </div>
        <div class="res-block">
            <div class="res-block-inner">
                <h3><?php echo $this->help ?></h3><br>
                <ul>
                    <li><a href="http://settings.svs-tv.lan" target="blank"><?php echo $this->help ?></a></li>
					<li><?php echo $this->office ?></li>
                    <li><?php echo $this->icq ?></li>
				</ul>
            </div>
        </div>
        <div class="res-block">
            <div class="res-block-inner">
                <h3><?php echo $this->network ?></h3><br>
                <ul>
                    <li>\\share.svs-tv.lan\files</li>
                    <li>\\share.svs-tv.lan\films</li>
                    <li>\\share.svs-tv.lan\films2</li>
                    <li>\\share.svs-tv.lan\films3</li>
                    <li>\\share.svs-tv.lan\films4</li>
                    <li>\\share.svs-tv.lan\games</li>
                    <li>\\share.svs-tv.lan\music</li>
				</ul>
            </div>
        </div>
        
    </div>
</div>