<div id="report">
    <div class="col-last">
        <?php foreach ($this->info_title as $title): ?>
            <div class="res-block">
                <div class="res-block-inner">
                    <h3><?php echo $this->escape($title['title']) ?></h3><br>
                    <ul>
                        <?php 
                            foreach ($title['items'] as $items): 
                            $text = $items['tpl'];
                            unset($items['tpl']);
                            foreach ($items as $k=>$v){                                
                                $text = preg_replace("/\{$k\}/",$this->escape($v),$text);
                            }
                        ?>
                            <li><?php echo $text?></li>
                        <?php endforeach; ?>
    				</ul>
                </div>
            </div>
        <?php endforeach; ?>
    </div>
</div>