<table>
	<tr>
		<td align='right'><?php echo $this->t_surname ?> :</td>
		<td><b><?php echo $this->surname ?></b></td>
	</tr>
	<tr>
		<td align='right'><?php echo $this->t_name ?> :</td>
		<td><b><?php echo $this->name ?></b></td>
	</tr>
	<tr>
		<td align='right'><?php echo $this->t_address ?> :</td>
		<td><b><?php echo $this->address ?></b></td>
	</tr>
	<tr>
		<td align='right'><?php echo $this->t_in_ip ?> :</td>
		<td><b><?php echo $this->in_ip ?></b></td>
	</tr> 
<!--
	<tr>
		<td align='right'><?php echo $this->t_in_pipe ?> :</td>
		<td><b><?php echo $this->in_pipe ?></b></td>
	</tr>
	<tr>
		<td align='right'><?php echo $this->t_out_pipe ?> :</td>
		<td><b><?php echo $this->out_pipe ?></b></td>
	</tr> -->
	<tr>
		<td align='right'><?php echo $this->t_email ?> :</td>
		<td><b><?php echo $this->email ?></b></td>
	</tr>
</table>
<hr>
<span class="notify"><?php echo $this->notify ?></span>