<table>
	<tr>
		<td align='right'><?php echo $this->t_tariffname ?> :</td>
		<td><b><?php echo $this->tariffname ?></b></td>
	</tr>
	<tr>
		<td align='right'><?php echo $this->t_dailyfee ?> :</td>
		<td><b><?php echo $this->dailyfee ?></b></td>
	</tr>
	<tr>
		<td align='right'><?php echo $this->t_monthlyfee ?> :</td>
		<td><b><?php echo $this->monthlyfee ?></b></td>
	</tr>
	<tr>
		<td align='right'><?php echo $this->t_freebyte ?> :</td>
		<td><b><?php echo $this->freebyte ?></b></td>
	</tr>
	<tr>
		<td align='right'><?php echo $this->t_bonus ?> :</td>
		<td><b><?php echo $this->bonus ?></b></td>
	</tr>
	<tr>
		<td align='right'><?php echo $this->t_mindeposit ?> :</td>
		<td><b><?php echo $this->mindeposit ?></b></td>
	</tr>
	<tr>
		<td align='right'><?php echo $this->t_freemblimit ?> :</td>
		<td><b><?php echo $this->freemblimit ?></b></td>
	</tr>
	<tr>
		<td align='right'><?php echo $this->t_dateofcheck ?> :</td>
		<td><b><?php echo $this->dateofcheck ?></b></td>
	</tr>
</table>
<hr>
<a href="javascript:;" onclick="Reports.showInTariff()"><?php echo $this->intariff ?></a>
